### ISSUE TITLE
When did default element properties change from "mod_petti" to "magpie_sc"?

### ISSUE THREAD

**Issue by sgbaird** [lrcfmd/ElMD#10]
My results started looking totally different and it seems to be because of the default `periodic_tab` `metric` between `ElMD` versions. I'm curious when this happened and if it was intentional.

Might be worth updating the release notes that correspond to when the change happened and/or issuing a warning in ElMD.__init__ until the next major release?

**Comment by SurgeArrester** [comment]
This was definitely a bug that was introduced when testing the new element dictionaries, some time last March, which was then rectified in May (v0.3.9). Do let me know if you see any other issues, as those additional element feaurizers definitely introduced some extra problems... 

I've updated the release notes on github to reflect those specific changes, but I'm not sure people will read those. There has been a major release in that time so I'm not sure about throwing out more terminal clutter, especially with the knock on effect that would have on ElM2D. I'm not sure there are that many active users of this library, but you're absolutely right it would be best to make it obvious to anyone who might be affected, so I'll leave this issue open for a few months to make it clearer to anyone else encountering the same problem.

**Comment by sgbaird** [comment]
Not sure if this is related https://github.com/lrcfmd/ElM2D/issues/10

**Comment by SurgeArrester** [comment]
I think that should be working in ElMD 0.4.5 now
