### ISSUE TITLE
Add functionality for computing distances between multiple compounds

### ISSUE THREAD

**Issue by sgbaird** [lrcfmd/ElMD#2]
E.g. pass in two arrays of strings and get an array of distances out

**Comment by SurgeArrester** [comment]
Hi there, thanks for raising this issue. I've put together a mapping class which should take care of all of that functionality for you. It's early release so please raise any issues on that github page if they do occur.

www.github.com/lrcfmd/ElM2D

Overloading methods gets messy in python, so I would prefer to keep this class cleaner I think. If you need a function to do this between 2 compositions then that can be defined separately in python:

```python
def elmd_2(x, y): 
    return ElMD(x).elmd(y)
```

If there is further interest for overloaded ElMD constructors these may be added later.
